name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      # Use env to silence warning during workflow
      # until actions @5 are released in June
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Publish to NPM
        run: npm publish --access public --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}